is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatCalcId
  - errors.clientOrAgentNotAuthorised
  - errors.ruleCalculationErrorMessagesExist
  - errors.notFoundRetrieveTaxCalc
  - errors.notFoundEoyEstimate
displayName: Retrieve Self Assessment Tax Calculation End Of Year Estimate [Test only]
description: This endpoint allows you to retrieve the end of year Income Tax and National Insurance contribution estimates for a given NINO and Calculation ID. Only applicable for an In-year calculation.<br><br> An error will occur if your calculation has one or more error messages. You can use the Retrieve Self Assessment Tax Calculation Messages endpoint to retrieve these messages.
(annotations.sandboxData): !include ../../scenarios/selfAssessment/retrieveEoyEstimate.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
 200:
   body:
     application/json:
       type: !include ../../schemas/selfAssessment/retrieveTaxCalc/retrieve_eoyEstimate_response.json
       examples:
         example-1:
          description: Retrieve End of Year Estimate
          value: !include ../../examples/selfAssessment/retrieveEoyEstimate/retrieve_response.json
   headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.