is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.incorrectOrEmptyBody
  - errors.ruleNoIncomeSubmissionExists
displayName: Trigger a Self Assessment Tax Calculation [Test only]
description: This endpoint allows the user to trigger a self-assessment tax calculation for a given tax year. It should be called whenever income data is updated through a periodic or annual endpoint. It can take up to 5 seconds for a Calculation ID to be returned when triggering a tax calculation. The result of the calculation can be seen using the "Retrieve Self Assessment Tax Calculation Metadata" endpoint.
(annotations.sandboxData): !include ../../scenarios/selfAssessment/trigger.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
 application/json:
   type: !include ../../schemas/selfAssessment/trigger/trigger.json
   examples:
     example:
       value: !include ../../examples/selfAssessment/trigger/trigger.json
responses:
 202:
   body:
     application/json:
       type: !include ../../schemas/selfAssessment/trigger/trigger_response.json
       example: !include ../../examples/selfAssessment/trigger/trigger_response.json
   headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.