description: "The tax year the data applies to, for example, 2017-18. The tax year must have ended. The start year and end year must not span two tax years. The minimum tax year is 2017-18. No gaps are allowed, for example, 2020-22 is not valid."
type: string
example: "2020-21"