#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: 'The format of the supplied NINO field is not valid.'
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: 'The format of the supplied taxYear value is not valid.'
                value:
                  code: FORMAT_TAX_YEAR
  formatFinalDeclaration:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatFinalDeclaration:
                description: 'The format of the supplied finalDeclaration value is not valid.'
                value:
                  code: FORMAT_FINAL_DECLARATION
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: 'The specified tax year is not supported, that is, the tax year specified is before the minimum tax year value.'
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeInvalid:
                description: 'Tax year range invalid. A tax year range of one year is required.'
                value:
                  code: RULE_TAX_YEAR_RANGE_INVALID
  ruleNoIncomeSubmissionExists:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNoIncomeSubmissionExists:
                description: 'A calculation could not be performed because no income data has been submitted against the tax year.'
                value:
                  code: RULE_NO_INCOME_SUBMISSIONS_EXIST
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  ruleFinalDeclarationReceived:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleFinalDeclarationReceived:
                description: 'Final declaration has already been received.'
                value:
                  code: RULE_FINAL_DECLARATION_RECEIVED