#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: 'The format of the supplied NINO field is not valid.'
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: 'The format of the supplied taxYear value is not valid.'
                value:
                  code: FORMAT_TAX_YEAR
  formatFinalDeclaration:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatFinalDeclaration:
                description: 'The format of the supplied finalDeclaration value is not valid.'
                value:
                  code: FORMAT_FINAL_DECLARATION
  formatCalcId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCalcId:
                description: 'The format of the supplied Calculation ID is not valid.'
                value:
                  code: FORMAT_CALC_ID
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: 'The specified tax year is not supported, that is, the tax year specified is before the minimum tax year value.'
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeInvalid:
                description: 'Tax year range invalid. A tax year range of one year is required.'
                value:
                  code: RULE_TAX_YEAR_RANGE_INVALID
  formatCalculationId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCalculationId:
                description: 'Invalid Calculation ID.'
                value:
                  code: FORMAT_CALCULATION_ID
  ruleNoIncomeSubmissionExists:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNoIncomeSubmissionExists:
                description: 'A calculation could not be performed because no income data has been submitted against the tax year.'
                value:
                  code: RULE_NO_INCOME_SUBMISSIONS_EXIST
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  ruleFinalDeclarationReceived:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleFinalDeclarationReceived:
                description: 'Final declaration has already been received.'
                value:
                  code: RULE_FINAL_DECLARATION_RECEIVED
  ruleIncomeSourcesChanged:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleIncomeSourcesChanged:
                description: 'Information relating to your income sources changed. You must trigger a new calculation using Intent to Submit a Final Declaration again before final declaration.'
                value:
                  code: RULE_INCOME_SOURCES_CHANGED
  ruleRecentSubmissionsExist:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleRecentSubmissionsExist:
                description: 'More recent submissions exist. You must trigger a new calculation using Intent to Submit a Final Declaration again before final declaration.'
                value:
                  code: RULE_RECENT_SUBMISSIONS_EXIST
  ruleResidencyChanged:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleResidencyChanged:
                description: 'Your residency has changed. You must trigger a new calculation using Intent to Submit a Final Declaration again before final declaration.'
                value:
                  code: RULE_RESIDENCY_CHANGED
  ruleIncomeSourcesInvalid:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleIncomeSourcesInvalid:
                description: 'There are no valid income sources.'
                value:
                  code: RULE_INCOME_SOURCES_INVALID
  ruleSubmissionFailed:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleSubmissionFailed:
                description: 'The submission cannot be completed due to validation failures.'
                value:
                  code: RULE_SUBMISSION_FAILED
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: 'The supplied income source could not be found.'
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND