#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  Type:
    enum: [info,warning,error]

traits:
  taxYear:
  finalDeclaration:
      queryParameters:
        finalDeclaration:
          type: boolean
          description: 'Must be sent as true when the user is ready to submit a final declaration.'
          required: false