#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  Type:
    enum: [info,warning,error]

traits:
  taxYearTys:
    queryParameters:
        taxYear:
          description: 'The tax year to which the data applies in the format YYYY-YY.<br><br>The minimum tax year is 2017-18. No gaps are allowed. For example, 2020-22 is not valid.<br><br>Where no tax year is provided, it will default to the current tax year.'
          example: "2023-24"
          required: false
  taxYear:
    queryParameters:
        taxYear:
          description: 'The tax year the data applies to, for example, 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2017-18. No gaps are allowed, for example, 2020-22 is not valid.'
          example: "2017-18"
          required: false
  finalDeclaration:
      queryParameters:
        finalDeclaration:
          type: string
          description: 'Must be sent as "true" when the user is ready to submit a final declaration. Acceptable values are "true" and "false".'
          required: false