is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.incorrectOrEmptyBody
  - errors.ruleNoIncomeSubmissionExists
displayName: Trigger a Self Assessment Tax Calculation [No longer available]
description: This resource is no longer available. It has been replaced by the Trigger a Self Assessment Tax Calculation endpoint in the <a href="/api-documentation/docs/api/service/individual-calculations-api/2.0">individual-calculations-api v2.0</a>.
(annotations.sandboxData): !include ../../scenarios/selfAssessment/trigger.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
 application/json:
   type: !include ../../schemas/selfAssessment/trigger/trigger.json
   examples:
     example:
       value: !include ../../examples/selfAssessment/trigger/trigger.json
responses:
 202:
   body:
     application/json:
       type: !include ../../schemas/selfAssessment/trigger/trigger_response.json
       example: !include ../../examples/selfAssessment/trigger/trigger_response.json
   headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
