#%RAML 1.0

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

title: Individual Calculations (MTD)
description: This is a draft spec for the Individual Calculations API.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/jsonfd

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Changelog
    content: !include docs/changelog.md
  - title: Support
    content: !include docs/support.md
  - title: Testing
    content: !include docs/testing.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

'/individual/calculations':
  /{nino}:
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /self-assessment:
    (annotations.group):
      name: Self Assessment
      description: !include docs/group_selfAssessment.md
    get: !include selfAssessment_list.raml
    post: !include selfAssessment_trigger.raml
    /{calculationId}:
      uriParameters:
        calculationId:
          description: "The unique identifier of the calculation. Must conform the regular expression':' ^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          type: string
          example: "f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c"
      get: !include selfAssessment_retrieve.raml
