#%RAML 1.0

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

title: Individual Calculations (MTD)
description: Trigger a self-assessment tax calculation, list self-assessment tax calculations for a tax year and retrieve a self-assessment tax calculation result using multiple endpoints.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

'/individuals/calculations':
  /{nino}:
    uriParameters:
      nino: !include pathParameters/nino.raml
    /self-assessment:
      (annotations.group):
        name: Self Assessment
        description: !include docs/group_selfAssessment.md
      get: !include endpoints/selfAssessment/list.raml
      post: !include endpoints/selfAssessment/trigger.raml
      /{calculationId}:
        uriParameters:
          calculationId:
            description: "The unique identifier of the calculation. Must conform the regular expression: `^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`"
            type: string
            example: "f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c"
        get: !include endpoints/selfAssessment/retrieveMetadata.raml
        /income-tax-nics-calculated:
          get: !include endpoints/selfAssessment/retrieveIncomeTaxAndNics.raml
        /taxable-income:
          get: !include endpoints/selfAssessment/retrieveTaxableIncome.raml
        /allowances-deductions-reliefs:
          get: !include endpoints/selfAssessment/retrieveAllowancesDeductionsReliefs.raml
        /end-of-year-estimate:
          get: !include endpoints/selfAssessment/retrieveEndOfYearEstimate.raml
        /messages:
          get: !include endpoints/selfAssessment/retrieveMessages.raml
  /crystallisation:
    (annotations.group):
      name: Crystallisation
      description: !include docs/group_crystallisation.md
    /{nino}:
      uriParameters:
        nino: !include pathParameters/nino.raml
      /{taxYear}:
        uriParameters:
          taxYear: !include pathParameters/taxYearMinimum2018.raml
        /intent-to-crystallise:
          post: !include endpoints/crystallisation/intentToCrystallise.raml
        /crystallise:
          post: !include endpoints/crystallisation/crystallise.raml