#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


traits:
  notFoundListCalculations:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFoundListCalculations:
                description: No tax calculations can be found for the supplied NINO and tax year
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  notFoundRetrieveMetadata:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFoundRetrieveMetadata:
                description: Tax calculation metadata could not be found for the supplied NINO and Calculation ID
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  notFoundRetrieveMessages:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFoundRetrieveMessages:
                description: A Tax Calculation could not be found for the supplied NINO and Calculation ID
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  noMessagesPresent:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              noMessagesPresent:
                description: A Tax Calculation was present, but messages were not found for the supplied NINO and Calculation ID
                value:
                  code: NO_MESSAGES_PRESENT
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO field is not valid
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The format of the supplied tax year field is not valid
                value:
                  code: FORMAT_TAX_YEAR
  formatCalcId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCalcId:
                description: The provided Calculation ID is not valid
                value:
                  code: FORMAT_CALC_ID
  formatType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatType:
                description: The provided type value is invalid
                value:
                  code: FORMAT_TYPE
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: An empty or non-matching body was submitted, this could be caused by a missing mandatory field
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeExceeded:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeExceeded:
                description: Tax year range exceeded. A tax year range of one year is required.
                value:
                  code: RULE_TAX_YEAR_RANGE_EXCEEDED
  ruleNoIncomeSubmissionExists:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNoIncomeSubmissionExists:
                description: A calculation could not be performed because no income data has been submitted against the tax year
                value:
                  code: RULE_NO_INCOME_SUBMISSIONS_EXIST

