#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  Type:
    enum: [info,warning,error]


traits:
  taxYear:
    queryParameters:
      taxYear:
        description: 'The tax year the data applies to, for example, 2019-20. <em>If no tax year is supplied calculations for the current tax year will be returned.</em> The start year and end year must not span two tax years. No gaps are allowed, for example, 2019-21 is not valid. The minimum tax year is 2017-18.'
        example: "2017-18"
        required: false
  'type':
    queryParameters:
      'type':
        type: Type
        description: "The 'type' query parameter allows the messages output to be filtered by type. The type parameter can be supplied more than once; e.g. ?type=info&type=warning."
        required: false



