is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeExceeded
  - errors.clientOrAgentNotAuthorised
  - errors.incorrectOrEmptyBody
  - errors.ruleNoIncomeSubmissionExists
displayName: Retrieve a Self Assessment Tax Calculation Metadata [test only]
description: The "Retrieve a Self Assessment Tax Calculation Metadata" endpoint allows users to retrieve high level calculation metadata for a given calculation ID. There will always be calculation metadata associated to a calculation ID that exists within HMRC.
(annotations.sandboxData): !include scenarios/selfAssessment/get.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
body:
 application/json:
   type: !include schemas/selfAssessment/trigger/trigger.json
   examples:
     example:
       value: !include examples/selfAssessment/trigger/trigger.json
responses:
 202:
   body:
     application/json:
       type: !include schemas/selfAssessment/trigger/trigger_response.json
       example: !include examples/selfAssessment/trigger/trigger_response.json
   headers:
     X-CorrelationId:
       example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
       description: Unique identifier of the transaction, String <br> Format∶ ^[A-Za-z0-9\-]{36}$.
