is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatCalcId
  - errors.formatType
  - errors.clientOrAgentNotAuthorised
  - errors.notFoundRetrieveTaxCalc
  - errors.noMessagesPresent
  - queryParameters.type
displayName: Retrieve Self Assessment Tax Calculation Messages [test only]
description: This endpoint allows you to retrieve 'info', 'warning' and 'error' level messages linked to a Calculation ID.  One or more error messages for a Calculation ID means a calculation could not be performed.  Vendor software should surface these messages to the end user.
(annotations.sandboxData): !include scenarios/selfAssessment/retrieveMessages.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
 200:
   body:
     application/json:
       type: !include schemas/selfAssessment/retrieveTaxCalc/retrieve_messages_response.json
       examples:
         example-1:
          description: Retrieve Calculation Messages with info messages
          value: !include examples/selfAssessment/retrieveMessages/retrieve_calc_messages_info.json
         example-2:
           description: Retrieve Calculation Messages with info and warning messages
           value: !include examples/selfAssessment/retrieveMessages/retrieve_calc_messages_info_and_warnings.json
         example-3:
            description: Retrieve Calculation Messages with warning and error messages
            value: !include examples/selfAssessment/retrieveMessages/retrieve_calc_messages_warnings_and_errors.json
         example-4:
            description: Retrieve Calculation Messages with error messages
            value: !include examples/selfAssessment/retrieveMessages/retrieve_calc_messages_errors.json
   headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.