is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatCalcId
  - errors.clientOrAgentNotAuthorised
  - errors.ruleCalculationErrorMessagesExist
  - errors.notFoundRetrieveTaxCalc
displayName: Retrieve Self Assessment Tax Calculation Income Tax and NICs Calculated [test only]
description: This endpoint allows you to retrieve the calculated Income Tax and National Insurance Contributions for a given NINO and Calculation ID.<br><br>An error will occur if your calculation has one or more error messages. You can use the Retrieve Self Assessment Tax Calculation Messages endpoint to retrieve these messages.
(annotations.sandboxData): !include scenarios/selfAssessment/retrieveIncomeTaxAndNics.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
 200:
   body:
     application/json:
       type: !include schemas/selfAssessment/retrieveTaxCalc/retrieve_incomeTaxAndNics_response.json
       examples:
         example-1:
            description: Example calculation response.
            value: !include examples/selfAssessment/retrieveIncomeTaxAndNics/retrieve_response.json
   headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
